<nav class="menu">
    <input type="checkbox" id="hamburger-checkbox" class="hamburger-checkbox">
    <label for="hamburger-checkbox" class="hamburger" tabindex="0">&#9776;</label>
    <ul class="nav">
        <li><a href="./index.php">Home</a></li>
        <li><a href="./jobs.php">Jobs</a></li>
        <li><a href="./apply.php">Apply</a></li>
        <li><a href="./about.php">About Us</a></li>
        <li><a href="./enhancements.php">Enhan1</a></li>
        <li><a href="./enhancements2.php">Enhan2</a></li>
        <li><a href="./manage.php">Manage</a></li>

    </ul>
    <div class="email_link" data-tooltip="Siwan Yu's email">
        <div class="individualEmail" data-tooltip="Siwan Yu's email">
            <a href="mailto:104577838@student.swin.edu.au">
                <img src="./styles/images/icon_menu_email_siwan.webp" alt="siwan's email, a black and white raven">
            </a>
        </div>
        <div class="individualEmail" data-tooltip="Sokunsana Ly 's email">
            <a href="mailto:104205032@student.swin.edu.au">
                <img src="./styles/images/icon_menu_email_sana.webp" alt="sana's email, a black and white raven">
            </a>
        </div>
        <div class="individualEmail" data-tooltip="Lorenzo Encena's email">
            <a href="mailto:105345670@student.swin.edu.au">
                <img src="./styles/images/icon_menu_email_lorenzo.webp" alt="lorenzo's email, a black and white raven">
            </a>
        </div>
    </div>
</nav>
</header>